  version: '3'
  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile-develop.dev
      ports:
        - "3001:3000"
      tty: true  
      volumes:
        - /app/node_modules
        - .:/app